source 'https://rubygems.org'

gem 'sinatra'
gem 'json'
gem 'activerecord'
gem 'sinatra-activerecord'

group 'development' do
  gem 'sqlite3'
  gem 'sinatra-sequel'
end

gem 'pg', :group => 'production'